### ISSUE TITLE
点开某个没标题的帖子crash

### ISSUE THREAD

**Issue by ashqal** [ZhangZhenghao/MaterialWeCenter#12]
> 02-16 09:19:31.476 17449-17449/com.zjut.material_wecenter E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                             Process: com.zjut.material_wecenter, PID: 17449
>                                                                             java.lang.NullPointerException
>                                                                                 at com.zjut.material_wecenter.controller.adapter.QuestionDetailAdapter.<init>(QuestionDetailAdapter.java:55)
>                                                                                 at com.zjut.material_wecenter.controller.activity.QuestionActivity$LoadAnswers.onPostExecute(QuestionActivity.java:187)
>                                                                                 at com.zjut.material_wecenter.controller.activity.QuestionActivity$LoadAnswers.onPostExecute(QuestionActivity.java:165)
>                                                                                 at android.os.AsyncTask.finish(AsyncTask.java:632)
>                                                                                 at android.os.AsyncTask.access$600(AsyncTask.java:177)
>                                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:136)
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5117)
>                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
>                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by zhenghaoz** [comment]
原来是那个空白的帖子是文章，解析不出来，点击就直接崩溃了，有空我修一下
