### ISSUE TITLE
建议添加搜索功能

### ISSUE THREAD

**Issue by y-young** [ZhangZhenghao/MaterialWeCenter#18]
建议在首页添加搜索功能

**Comment by zhenghaoz** [comment]
了解，完成后告知

**Comment by zhenghaoz** [comment]
搜索功能添加完毕，参考[添加搜索功能](https://github.com/ZhangZhenghao/MaterialWeCenter/commit/87960c41a38bfd5fb4cb2333a2879de1761ca068)
