### ISSUE TITLE
无网络时程序崩溃

### ISSUE THREAD

**Issue by y-young** [ZhangZhenghao/MaterialWeCenter#19]
当无网络链接时打开答案详情页程序崩溃, answer Detail为null,报空指针异常

**Comment by zhenghaoz** [comment]
@Y-Young 不是很优雅地解决了这个问题，反正这个页面以后要改进的

**Comment by y-young** [comment]
@ZhangZhenghao 准备怎么改进？

**Comment by zhenghaoz** [comment]
@Y-Young 原来的富文本支持方式是有问题的，所以改进富文本的显示比较重要

**Comment by y-young** [comment]
@ZhangZhenghao 我试了下WebView显示，效果还行，就是图片比较麻烦

**Comment by dartick** [comment]
@Y-Young 这部分是存在很多问题，可以尝试这个富文本库，https://github.com/zzhoujay/RichText

**Comment by y-young** [comment]
@Dartick 看起来不错。你自己解决了哪些问题，能不能分享一下？

**Comment by dartick** [comment]
@Y-Young 现在暂时没有新的发现。

**Comment by zhenghaoz** [comment]
@Y-Young 富文本支持修改完毕
