### ISSUE TITLE
发布问题可以添加分类吗？

### ISSUE THREAD

**Issue by 0312birdzhang** [ZhangZhenghao/MaterialWeCenter#21]
因为论坛设置了问题必须有分类，所以导致客户端不能发布 😂

**Comment by zhenghaoz** [comment]
发布问题的API是支持的，但是并没有获取分类的API，这就尴尬了，所以项目也就没有分类支持。目前没有太多时间修改，下次更新估计很远😂

**Comment by 0312birdzhang** [comment]
我也找了一下api，没看到有获取分类的。。这™就尴尬了
然后我加了一句代码，<code>params.put("category_id", "99");</code>，发现也不管用，必须是**int**类型才行。。。⊙﹏⊙‖∣
