### ISSUE TITLE
輸入東西時SNACKBAR會被輸入法遮蓋

### ISSUE THREAD

**Issue by ckc** [ZhangZhenghao/MaterialWeCenter#26]
首先謝謝你開源供大家學習
剛下了試您演示apk，發現SNACKBAR會被遮蓋
看看能不加如下類似的？
android:layout_alignParentBottom="true"

**Comment by zhenghaoz** [comment]
感謝反饋，我添加了android:windowSoftInputMode="adjustResize"，更新了代碼和DEMO：#27
